7-7-2/DDocker_BE

config/index.js
controllers/posts-controller.js
loaders/db.js
models/posts-db.js
package.json
pnpm-lock.yaml
routes/posts-route.js
services/post-service.js

getPostDetail 및 mysql2 migration입니다. 

---

controllers/brand-controller.js
models/brand-db.js
package.json
routes/brand-route.js
services/brand-service.js

feat: brand data fetched

---

controllers/posts-controller.js
loaders/db.js
models/posts-db.js
routes/posts-route.js
services/post-service.js

Feat: postRegister

---

app.js
controllers/posts-controller.js
middlewares/errorHandler.js
middlewares/validatePostForm.js
models/posts-db.js
routes/posts-route.js
services/post-service.js

Feat: errorHandler/validatePostForm

---

controllers/posts-controller.js
middlewares/buildPatchQuery.js
models/posts-db.js
routes/coffee-route.js
routes/posts-route.js
services/post-service.js
swagger-output.json

Feat: deletePost/updatePost/writeComment

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

closes #15 
- authMiddleware 에서 전달된 JWT payload userId 사용

Feat: edit user profile

---

controllers/user-controller.js
middlewares/authMiddleware.js
models/user-db.js
routes/users-route.js
services/user-service.js

closes #26 
- user nickname 중복검사
`users/check?nickname={nickname}`
`검색결과 있는경우 ? true : false `

Feat: nickname 중복검사

---

controllers/user-controller.js
models/user-db.js
package.json
pnpm-lock.yaml
routes/users-route.js
services/user-service.js

closes #30
JWT accessToken public_id 사용은 기존 userId 사용 방식과 동일

Feat: public id 생성 및 accessToken payload 변경

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

Feat: getUserPosts

---

controllers/posts-controller.js
models/posts-db.js
routes/posts-route.js
services/post-service.js
swagger-output.json

feat: getComments/getReply

---

controllers/follow-controller.js
middlewares/validatePostForm.js
models/follow-db.js
models/follow-queries.js
models/posts-queries.js
models/query-fns.js
routes/follow-route.js
services/follow-service.js

feat: follow fns

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js
swagger-output.json

Feat: getUserFollowsCount 

---

controllers/posts-controller.js
middlewares/validatePostForm.js
models/posts-db.js
models/posts-queries.js
models/query-fns.js
routes/posts-route.js

feat: apply auth to posts API

---

controllers/coffee-controller.js
models/coffee-db.js
routes/coffee-route.js
services/coffee-service.js
swagger-output.json

closes #27
기존의 `getCoffeeInfo` 호출 시 가져오는 데이터 변경
- before
- after
<br />
<br />
`getCalendar` 호출 시,
`created_at` 기준 현재 날짜를 `Calendar` 배열 내부에서 월 데이터 객체에 종속되어 반환 
👉 일간 누적 카페인량 조회

Feat: Calendar

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

Refactor: user-routes errorHandler 적용

---

controllers/follow-controller.js
controllers/likes-controller.js
controllers/posts-controller.js
models/follow-db.js
models/likes-db.js
models/likes-queries.js
models/posts-db.js
models/posts-queries.js
models/query-fns.js
routes/likes-route.js
routes/posts-route.js
services/likes-service.js
services/post-service.js
swagger-output.json

Feat: getFollowingPosts

---

models/coffee-db.js
routes/brand-route.js
routes/coffee-route.js
routes/search-route.js
services/brand-service.js
services/coffee-service.js
services/search-service.js
swagger-output.json

Refactor: common errorHandler & BL modify

---

controllers/likes-controller.js
controllers/posts-controller.js
models/posts-db.js
models/posts-queries.js
routes/posts-route.js
services/post-service.js

feat: getSocialCounts

---

controllers/posts-controller.js
models/posts-db.js
models/posts-queries.js
routes/posts-route.js
services/post-service.js
swagger-output.json

feat: getPopular

---

controllers/user-controller.js
models/user-db.js
services/user-service.js

Refactor: redirect url, getUserInfo res

---

controllers/coffee-controller.js
models/coffee-db.js
routes/coffee-route.js
services/coffee-service.js

Refactor: Coffee Auth middleware, getCoffeeInfo 수정

---

config/index.js
controllers/likes-controller.js
controllers/posts-controller.js
loaders/express.js
middlewares/switchBrand.js
models/likes-db.js
models/likes-queries.js
models/posts-queries.js
routes/likes-route.js
services/likes-service.js
services/post-service.js

Feat: getMyLikeOnPost

---

models/posts-queries.js
routes/likes-route.js
services/post-service.js

fix: getFollowingPosts && getMyLikeOnPost

---

controllers/brand-controller.js
models/brand-db.js
models/coffee-db.js
services/brand-service.js

Fix: getBrandData

---

controllers/posts-controller.js
models/posts-db.js
models/posts-queries.js
routes/posts-route.js
services/post-service.js

Feat: modify getFollowingPosts for Infinite Scroll

---

routes/posts-route.js

Feat: getFollowingPosts route

---

controllers/posts-controller.js
middlewares/validatePostForm.js
models/brand-db.js
models/posts-db.js

Fix: POST comment req.body structure

---

controllers/posts-controller.js
controllers/user-controller.js
models/posts-db.js
models/user-db.js

- RegisterPost res값 userId 추가
- getUserPost db-res 값 형식 변경 
- getUserInfo logic 수정
- #### 🪴 closed #72

Fix: RegisterPost, getUserPost, getUserInfo

---

ecosystem.config.js
loaders/db.js
models/coffee-db.js

close #74 
- 이번엔 해당이슈 읽어주세요 중요합니다

Fix: coalesce null value in coffee api && db connection config

---

controllers/search-controller.js
controllers/user-controller.js
models/search-db.js

refactor: search for debounced search

---

controllers/brand-controller.js
controllers/posts-controller.js
models/brand-db.js
models/brand-queries.js
models/posts-db.js
models/posts-queries.js
routes/brand-route.js
routes/posts-route.js
services/brand-service.js
services/post-service.js

Feat: trend APIs

---

middlewares/validatePostForm.js
models/user-db.js

- getUserInfo && user-db AboutMe column 가져오는 query 추가
- validatePostForm 필수 항목 수정
- #### 🪴 closed #80

Feat: getUserInfo && AboutMe column

---

models/brand-queries.js

fix: trend week condition

---

models/posts-queries.js

fix: getDailyPopular with postId

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

- getUserInfo && authMiddleware && !params
- #### 🪴 closed #89

Feat: getUserInfo(MyProfile) api 

---

controllers/search-controller.js
models/search-db.js
routes/search-route.js
services/search-service.js

feat: getSearchListMore

---

controllers/coffee-controller.js
models/coffee-db.js
routes/coffee-route.js
services/coffee-service.js
services/user-service.js

- getCalendar YYYY-MM params > 월별 데이터 조회
- getCalendar res {day: MM-DD, caffeineSum: string } 수정
- #### 🪴 closed #93

Feat: getCalendar api

---

middlewares/validatePostForm.js
models/posts-db.js
services/user-service.js

feat: receive registerPost postId from client && include userId on setUserOauth res

---

middlewares/switchBrand.js
middlewares/validatePostForm.js
models/posts-db.js
models/posts-queries.js
services/user-service.js

feat: include postId value in getPostDetail

---

controllers/posts-controller.js
models/posts-queries.js

- getWeeklyPopularList && date 1일 기준으로 인기 순위 업데이트
- #### 🪴 closed #101

Feat: getWeeklyPopularList && date

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

-  deleteUserAccount.api
- #### 🪴 closed #103

Feat: deleteUserAccount.api

---

controllers/report-controller.js
models/report-db.js
routes/report-route.js
services/report-service.js

- CREATE report table
- issue 확인 부탁드립니다
- postReport api
- #### 🪴 closed #104

Feat: postReport api

---

controllers/user-controller.js
models/user-db.js
services/user-service.js

- delete gender 
- fix setUserInit sql
- #### 🪴 closed #107

Fix: setUserInit api

---

controllers/follow-controller.js
controllers/likes-controller.js
controllers/notification-controller.js
controllers/posts-controller.js
controllers/user-controller.js
ecosystem.config.js
loaders/express.js
middlewares/redisQueue.js
models/follow-db.js
models/likes-db.js
models/likes-queries.js
models/posts-db.js
models/posts-queries.js
models/user-db.js
package.json
pnpm-lock.yaml
routes/notification-route.js
routes/users-route.js
services/user-service.js

close #109
.env에 Redis관련 변수 추가 확인 필요합니다! @cuconveniencestore

feat: redis-notification

---

controllers/report-controller.js
models/coffee-db.js
models/report-db.js
routes/report-route.js
services/report-service.js

feat: report comment

---

models/user-db.js
services/user-service.js

- Oauth => Remove default profile Image
- #### 🪴 closed #113

Fix: setUserOauth && Remove default profile Image

---

controllers/user-controller.js
models/user-db.js
routes/users-route.js
services/user-service.js

feat: remove getUserProfile

---

models/likes-db.js
models/likes-queries.js
models/posts-db.js
models/posts-queries.js

- post-queries 수정 
- 좋아요/댓글 senderId/nickname 불일치 수정
close #120

feat: optimize post-queries

---

controllers/brand-controller.js
loaders/index.js
loaders/redis.js
models/brand-db.js
models/brand-queries.js

- 브랜드 데이터 서버 시작시 Redis 캐싱 처리 후 프론트 전송
close #119

feat: cache brand data with Redis

---

controllers/brand-controller.js
controllers/support-controller.js
loaders/redis.js
models/support-db.js
models/support-queries.js
routes/support-route.js
services/support-service.js

- Support
- Notice && FAQ
- #### 🪴 closed #123

Feat: support

---

controllers/notification-controller.js

Feat: add heartbeat interval to keep notification connection

---

.github/workflows/deploy.yaml
config/index.js
package.json
pnpm-lock.yaml

feat: set up CI/CD

---

.github/workflows/deploy.yaml

Fix: deploy script

---

.github/workflows/deploy.yaml

Fix: deploy scenario

---

.github/workflows/deploy.yaml

Fix: script mysql root access

---

middlewares/switchBrand.js

feat: add new brands in brandMap

---

controllers/notification-controller.js

fix: specify notification access control allow origin

---

controllers/user-controller.js

Fix: editProfile

---

controllers/posts-controller.js
middlewares/generateStorageURL.js
models/posts-queries.js
package.json
pnpm-lock.yaml
routes/posts-route.js
services/post-service.js

feat: migrate R2 functions from client to server

---

middlewares/switchBrand.js
models/posts-queries.js

Fix: add size and intensity in postcard data
